//
//  Groups.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Groups: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _userId: String?
    @objc var _groupId: String?
    @objc var _category: String?
    @objc var _creationDate: NSNumber?
    @objc var _isBrandInvited: NSNumber?
    @objc var _members: Set<String>?
    @objc var _name: String?
    
    class func dynamoDBTableName() -> String {

        return "urinvited-mobilehub-83094118-Groups"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_groupId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_groupId" : "groupId",
               "_category" : "category",
               "_creationDate" : "creationDate",
               "_isBrandInvited" : "isBrandInvited",
               "_members" : "members",
               "_name" : "name",
        ]
    }
}
