//
//  Messages.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Messages: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _userId: String?
    @objc var _groupId: String?
    @objc var _content: String?
    @objc var _creationDate: NSNumber?
    @objc var _profilePicture: String?
    @objc var _username: String?
    
    class func dynamoDBTableName() -> String {

        return "urinvited-mobilehub-83094118-Messages"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_groupId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_groupId" : "groupId",
               "_content" : "content",
               "_creationDate" : "creationDate",
               "_profilePicture" : "profilePicture",
               "_username" : "username",
        ]
    }
}
